import { describe, expect, it } from 'vitest';
import derivedData from '../../data/combat-derived.json';
import { ROSTER } from '../shipdefs';
import { DAMAGE_DIE, GUNS, hitChance, type GunKind } from '../navycombat';

/**
 * The engine, checked against the spreadsheet's own arithmetic.
 *
 * Sean's Fleet Roster grew a **Combat Derived Stats** tab, which computes, for
 * every hull, what each kind of gun scores against her and what her own volley
 * averages before armor. That is the same sum `navycombat.ts` does, worked
 * independently in a different tool — so it is the one check available that is
 * not the engine marking its own homework.
 *
 * The matrices were compared by eye when the tab arrived and matched. This is
 * that comparison made permanent and exhaustive: twenty-five hulls, three gun
 * types, both directions. If a modifier is ever edited on one side only, a
 * dozen of these fail and name the ship.
 *
 * `combat-derived.json` is a verbatim copy of the tab, regenerated by
 * re-reading the sheet and never edited by hand.
 */
const derived = derivedData.derived as Record<
  string,
  {
    lightHit: number;
    longHit: number;
    heavyHit: number;
    longVolley: number;
    heavyVolley: number;
    lightVolley: number;
    rawVolley: number;
    combatant: string;
  }
>;

/** The average of n d20, which is what the sheet's volley columns assume. */
const avgDice = (n: number) => (n * (DAMAGE_DIE + 1)) / 2;

describe("the sheet's own combat arithmetic", () => {
  it('covers every hull in the roster, and no ship the roster has lost', () => {
    expect(Object.keys(derived).sort()).toEqual(ROSTER.ships.map((s) => s.id).sort());
  });

  it('agrees with hitChance for every gun against every hull', () => {
    for (const ship of ROSTER.ships) {
      const row = derived[ship.id];
      const pairs: Array<[GunKind, number]> = [
        ['Light', row.lightHit],
        ['Long', row.longHit],
        ['Heavy', row.heavyHit],
      ];
      for (const [kind, sheet] of pairs) {
        // `hitChance` works in points out of a hundred, as the sheet does.
        expect(hitChance(kind, ship), `${ship.name} vs ${kind}`).toBe(sheet);
      }
    }
  });

  it('agrees on what each hull throws in a volley, before armor', () => {
    for (const ship of ROSTER.ships) {
      const row = derived[ship.id];
      /*
       * Guns times average dice, and no hit chance in it.
       *
       * Worth stating, because the column name does not say so and the first
       * reading of it here was wrong: the sheet calls these *"pre-armor
       * average damage"*, and they turn out to be pre-accuracy as well — the
       * Wayfinder's two light guns come out at 42, which is 2 × 21 flat and
       * not 85% of it. So the column measures what a hull throws, not what
       * lands. That is the right yardstick for comparing two hulls' batteries,
       * and it is emphatically not expected damage.
       */
      const own = (kind: GunKind, guns: number) => guns * avgDice(GUNS[kind].dice);

      expect(own('Long', ship.guns.longGuns), `${ship.name} long`).toBeCloseTo(row.longVolley, 1);
      expect(own('Heavy', ship.guns.heavyGuns), `${ship.name} heavy`).toBeCloseTo(row.heavyVolley, 1);
      expect(own('Light', ship.guns.lightGuns), `${ship.name} light`).toBeCloseTo(row.lightVolley, 1);
      expect(
        own('Long', ship.guns.longGuns) +
          own('Heavy', ship.guns.heavyGuns) +
          own('Light', ship.guns.lightGuns),
        `${ship.name} raw`,
      ).toBeCloseTo(row.rawVolley, 1);
    }
  });

  it('agrees on which hulls are warships and which are not', () => {
    for (const ship of ROSTER.ships) {
      expect(ship.combatantType, ship.name).toBe(derived[ship.id].combatant);
    }
  });
});
